print("Welcome to the Band Name Generator!")
city=input("What is the name of the city you grew up in?")
pet=input("What was the name of your first pet?")
print("Your band name could be "+city+" "+pet)
print("Cool!")
